language: c

sudo: required

script:
  - uname -s && python -V
  # - autoreconf -iv
  #- ./configure
  #- make check
  #- ls python -lRA
  #- cd ./python
  # - sudo python setup.py install
  # - sudo pip install -v  
  - sudo pip install https://github.com/pySART/pyccp/archive/master.tar.gz
  #- cd ..
  - ls
  - cd ./tests
  - make
  #- sudo pip install enum
  #- sudo pip install -r requirements.txt
  #- ls -lA
  #- python -c "import pyccp; print(dir(pyccp))"
  - python -m unittest discover -v

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

notifications:
  email: false

#matrix:
#  allow_failures:
#    - os: osx

